spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5432/swiftlogistics_authdb
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: supersecretkeysupersecretkeysupersecretkey
  expiration: 3600000

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.security: DEBUG
