spring:
  application:
    name: ros-service

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/swiftlogistics_rosdb
    username: rosdbuser
    password: "rosdb123"
    driver-class-name: org.postgresql.Driver
    
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update  # This will create/update tables automatically
    show-sql: true      # Show SQL queries in console (useful for development)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Connection Pool Configuration
  hikari:
    connection-timeout: 20000
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 300000

# Server Configuration
server:
  port: 8083  # Different port from auth-service (8081) and other services

# Logging Configuration
logging:
  level:
    com.swiftlogistics.ROS: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Application specific configurations
app:
  optimization:
    default-algorithm: DISTANCE_BASED
    max-deliveries-per-route: 20
    max-route-distance: 100.0  # in kilometers
    default-vehicle-speed: 40  # km/h for time calculations
