spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/swiftlogistics_orderdb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  redis:
    host: localhost
    port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  application:
    name: order-service

jwt:
  secret: supersecretkeysupersecretkeysupersecretkey
  expiration: 3600000

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry:  true
    register-with-eureka: true

  instance:
    prefer-ip-address: true

logging:
  level:
    org:
      springframework:
        security=DEBUG:


